create database HEROVIRED_rgm;
 CREATE TABLE RGM_1 (
 RGM_NAME varchar(25) NOT NULL,
 RGM_COLLEGE VARCHAR(30) NOT NULL,
 RGM_SESION varchar(25) NOT NULL,
 RGM_CONTACT INT NOT NULL,
 RGM_BRANCH VARCHAR(25) NOT NULL,
 RGM_TRAINER varchar(30) NOT NULL
 );
SELECT * FROM RGM

INSERT INTO RGM VALUES ("SAMRIN","RGM","PYTHON",874897,"ECE","ANIK");
SELECT * FROM RGM